version: "3.9"

services:
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
